find_path(LIBMAGIC_INCLUDE_DIR  NAMES magic.h
  PATHS
  /usr/include
  /usr/local/include
  )

find_library(LIBMAGIC_LIBRARIES NAMES magic
  PATHS
  /usr/lib
  /usr/local/lib
  )

if (LIBMAGIC_INCLUDE_DIR AND LIBMAGIC_LIBRARIES)
  set(LIBMAGIC_INCLUDE_DIRS ${LIBMAGIC_INCLUDE_DIR})
endif (LIBMAGIC_INCLUDE_DIR AND LIBMAGIC_LIBRARIES)

if(LIBMAGIC_INCLUDE_DIRS AND LIBMAGIC_LIBRARIES)
  set(HAVE_LIBMAGIC TRUE CACHE INTERNAL "libmagic found")
  message(STATUS "Found libmagic")
else(LIBMAGIC_INCLUDE_DIRS AND LIBMAGIC_LIBRARIES)
  set(HAVE_LIBMAGIC FALSE CACHE INTERNAL "libmagic found")
  message(STATUS "Not found libmagic")
endif(LIBMAGIC_INCLUDE_DIRS AND LIBMAGIC_LIBRARIES)

mark_as_advanced(LIBMAGIC_INCLUDE_DIR LIBMAGIC_INCLUDE_DIRS LIBMAGIC_LIBRARIES)
